import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className="antialiased"
          data-new-gr-c-s-check-loaded="14.1229.0"
          data-gr-ext-installed=""
          cz-shortcut-listen="true"
        >
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
